#!/usr/bin/env python
# -*- coding: UTF-8 -*-
'''packdata.py'''

import code.packHelper as helper
import xml.etree.ElementTree as et

PICQUALITY = "80"
BACKQUALITY = "80"
class PackData(object):
	"""docstring for PackData"""
	def __init__(self, modpath):
		data = self.getachive(modpath)
		self.subdir = data['subdir']
		self.status = data['status']

	def getachive(self,modpath):
		dirs = helper.scanDir(modpath, withpath=False)

		path = helper.genPath(modpath, dirs[0])
		status = helper.scanDir(path,withpath=False)
		files = helper.scanFile(path,withpath=False)
		return dict(subdir=dirs, status=dict(dir=status, file=files))


	@staticmethod
	def genroot(modname):   #modname = commando ...
		rootname = modname+'.fla'
		root = et.Element('root',{'doc_name': rootname})
		return root

	# def wxml(self, replace):
	# 	root = self.genroot()
	# 	titem = self.witem(root)
	# 	self.wlabel(replace, titem)
	# 	self.wpics(replace, titem)

	# 	root = helper.indent(root)
	# 	et.ElementTree(root).write(self.jsfl+'/'+self.xmlname)
	# 	return self.jsfl+'/'+self.xmlname.replace('.xml','.jsfl')
	
	@staticmethod
	def savexml(root,fname):
		root = helper.indent(root)
		et.ElementTree(root).write(fname)

	@staticmethod
	def countPics(modpath, subdir, status): #modpath = command xxx
		pngnums =dict()
		# print(dirs)
		for dirname in subdir:      # subdir = 1_2 , xx
			path = modpath +'/'+ dirname
			newstatus = dict()

			newstatus['file'] = len(status['file'])

			for sdir in status['dir']: #sdir = 1_idle
				spath = path + '/' + sdir
				file = helper.scanFile(spath)
				newstatus[sdir] = len(file)

			pngnums[dirname] =newstatus
			
		return pngnums

	@staticmethod
	def getitems(ttxml, subdir,replace):
		tmp = helper.scanFile(ttxml)
		xmlpath = dict()
		for i in tmp:
			if i[-3:] == 'xml':
				ibn = helper.baseName(i)
				xmlpath[ibn[:-4]]=i

		pngxy = dict()
		subdir.extend(sorted(replace.keys()))

		for dirname in subdir:
			if dirname in replace.keys():
				newdirname = replace[dirname]
			else:
				newdirname = dirname
			# print(newdirname, dirname)
			pngxy[dirname] = PackData.getxy(xmlpath[newdirname])
		return pngxy

	@staticmethod
	def getxy(path):
		ttxml = et.parse(path)
		root = ttxml.getroot()

		tmplist = list()
		for subtt in root:
			pngpath = subtt.get('name')
			# print(pngpath)
			if 'background' in pngpath:
				xname = 'background'
				xpath = pngpath
			else:
				tmp = pngpath.split('/')
				xpath, xname = tmp[0], tmp[1]

			frameWidth = int(subtt.get('frameWidth'))
			frameHeight = int(subtt.get('frameHeight'))
			frameX = int(subtt.get('frameX'))
			frameY = int(subtt.get('frameY'))
			width = int(subtt.get('width'))
			height = int(subtt.get('height'))
			x = abs(frameX)-frameWidth/2
			y = abs(frameY)-frameHeight/2
			dd = dict(xname=xname, xpath=xpath, x=x,y=y, width=width, height=height)

			tmplist.append(dd)
		return tmplist

	@staticmethod
	def genjsfl(modname, jsflpath):
		xmlname = modname+'.xml'
		modname = helper.genPath(jsflpath,modname+'.jsfl')
		text = "//auto generated by python\n"
		text += "var file = fl.configURI + 'KPJSFL/CreateScript.jsfl';\n"
		text += "fl.runScript(file);\n"
		text += "var config_path = get_current_path()+'%s';\n"
		text += "create_doc_path(config_path)\nfl.quit()"

		with open(modname, 'w') as fl:
			fl.write(text % xmlname)

	@staticmethod
	def witem(root, types='movie', iname='mc', lname='AnimationClip'):
		return et.SubElement(root, types, {'item_name':iname, 'link_name': lname})
		
	#pngnums like pngnums['1_2']{'file':[], '1_idle': 24}
	@staticmethod
	def wlabel(dirname, pngnums, status, replace, titem, index = 0):
		layer = et.SubElement(titem,'layer',{'name':'label'})
		pre = dirname.split('_')[-1]
		if dirname in replace.keys():
			item = pngnums[replace[dirname]]
		else:
			item = pngnums[dirname]

		for k in status['dir']:    #status['dir'] =['1_2', 'x_x' ...]
			v = item[k]
			name = pre+k[1:]
			et.SubElement(layer, 'frame',  {'start_index':str(index+1), 
											'end_index': str(index+v), 
											'label':name})
			index += v
		return index

	#pngxy like pngxy['1_2'] [{'xname':'xx', 'xpath':'1_idle','x':x, 'y':y}]
	@staticmethod
	def wpics(dirname, pngxy, replace, mpath, titem, index=1):
		layer = et.SubElement(titem,'layer',{'name':'pics'})

		scalex = False
		backpngs =list()
		if dirname in replace.keys():
			dirname = replace[dirname]
			scalex = True
		for item in pngxy[dirname]:
			backpng = dict()
			xname = item['xname']
			x = item['x']
			y = item['y']
			xpath = item['xpath']
			width = item['width']
			height = item['height']
			path = mpath +'/'+ dirname
			

			if xname != 'background':
				path = path +'/'+ xpath
				path = path +'/'+ xname+'.png'
				if not scalex:
					et.SubElement(layer, 'frame', {'quality':PICQUALITY, 'x':str(x), 'y':str(y), 
						'source_path':path, 
						'start_index':str(index), 'end_index':str(index)})
				else:
					et.SubElement(layer, 'frame', {'quality':PICQUALITY, 'x':str(x*(-1)-width), 'y':str(y), 
						'source_path':path, 'scaleX':'-1', 
						'start_index':str(index), 'end_index':str(index)})
			else:
				backpng['x'] = x
				backpng['y'] = y
				backpng['width'] = width
				backpng['height'] = height
				backpng['path'] = path +'/'+ xname+'.png'
				backpng['count'] = index-1
				backpngs.append(backpng)
			index += 1

		return backpngs

	@staticmethod
	def wbackground(backpngs,titem):
		layer = et.SubElement(titem,'layer',{'name':'background'})
		index = 0

		for backpng in backpngs:
			et.SubElement(layer, 'frame', {'quality':BACKQUALITY, 'x':str(backpng['x']), 'y':str(backpng['y']), 
						'source_path':backpng['path'], 
						'start_index':str(index+1), 'end_index':str(backpng['count'] + index)})
			index += backpng['count']
